dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - env: COMPILER=g++-8 BUILD=Debug STANDARD=17
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CXX=${COMPILER}; fi
  - mkdir build && cd build

script:
  - cmake .. && cmake --build .
  - cd algorithms_test/ && ./algorithm_sort_unit_tests