openapi: "3.0.0"
info:
  version: 1.0.0
  title: Register Replication
  description: Distributed Algorithms. Atomic snapshots and ABD
paths:
  /v1/register/replica:
    post:
      description: Write a new register value to the replica
      operationId: WriteRegisterValueToReplica
      requestBody:
        description: A new register value
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterValue'
      responses:
        '200':
          description: The new value was successfully written to the replica
        '400':
          description: The input data contains incorrect values for writing the value to the register
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      description: Read a current register value
      operationId: ReadRegisterValueFromReplica
      responses:
        '200':
          description: The register value was successfully read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterValue'
        '404':
          description: The register is not initialized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

  /v1/register/coordinator:
    post:
      description: Write a new register value to the coordinator
      operationId: WriteRegisterValueToCoordinator
      requestBody:
        description: A new register value
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterValue'
      responses:
        '200':
          description: The new value was successfully written to the coordinator
        '400':
          description: The input data contains incorrect values for writing the value to the register
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
    get:
      description: Read a current register value
      operationId: ReadRegisterValueFromCoordinator
      responses:
        '200':
          description: The register value was successfully read
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterValue'
        '404':
          description: The register is not initialized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    RegisterValue:
      type: object
      required:
        - value
        - timestamp
      properties:
        value:
          type: integer
          format: int32
          description: Register value
        timestamp:
          type: integer
          format: int64
          minimum: 0
          description: Register timestamp

    ErrorMessage:
      type: object
      required:
        - error_message
      properties:
        error_message:
          type: string
          description: Error message
